In [1]:
import pandas as pd

## Read in all the 2018 CSVs, check dates

In [4]:
# Categories: DayOfWeek, FlightDate, Reporting_Airline, Tail_Number
# OriginAirportID, Origin, OriginCityName, OriginState
# DestAirportID, Dest, DestCityName, DestState, DepTime, DepDelay
# ArrDelay, CarrierDelay, WeatherDelay, NASDelay, SecurityDelay, LateAircraftDelay
df18_1 = pd.read_csv('data/jan_2018.csv')
df18_2 = pd.read_csv('data/feb_2018.csv')
df18_3 = pd.read_csv('data/march_2018.csv')
df18_4 = pd.read_csv('data/april_2018.csv')
df18_5 = pd.read_csv('data/may_2018.csv')
df18_6 = pd.read_csv('data/june_2018.csv')
df18_7 = pd.read_csv('data/july_2018.csv')
df18_8 = pd.read_csv('data/aug_2018.csv')
df18_9 = pd.read_csv('data/sept_2018.csv')

In [6]:
# df18_5.head()

## Read in 2017 CSVs

In [9]:
df17_1 = pd.read_csv('data/jan_2017.csv')
df17_2 = pd.read_csv('data/feb_2017.csv')
df17_3 = pd.read_csv('data/march_2017.csv')
df17_4 = pd.read_csv('data/april_2017.csv')
df17_5 = pd.read_csv('data/may_2017.csv')
df17_6 = pd.read_csv('data/june_2017.csv')
df17_7 = pd.read_csv('data/july_2017.csv')
df17_8 = pd.read_csv('data/aug_2017.csv')
df17_9 = pd.read_csv('data/sept_2017.csv')
df17_10 = pd.read_csv('data/oct_2017.csv')
df17_11 = pd.read_csv('data/nov_2017.csv')
df17_12 = pd.read_csv('data/dec_2017.csv')

In [22]:
# df17_12.head()

## Read in 2016 CSVs

In [23]:
df16_1 = pd.read_csv('data/jan_2016.csv')
df16_2 = pd.read_csv('data/feb_2016.csv')
df16_3 = pd.read_csv('data/march_2016.csv')
df16_4 = pd.read_csv('data/april_2016.csv')
df16_5 = pd.read_csv('data/may_2016.csv')
df16_6 = pd.read_csv('data/june_2016.csv')
df16_7 = pd.read_csv('data/july_2016.csv')
df16_8 = pd.read_csv('data/aug_2016.csv')
df16_9 = pd.read_csv('data/sept_2016.csv')
df16_10 = pd.read_csv('data/oct_2016.csv')
df16_11 = pd.read_csv('data/nov_2016.csv')
df16_12 = pd.read_csv('data/dec_2016.csv')

In [36]:
# df16_12.head()

## Read in 2015 CSVs

In [37]:
df15_1 = pd.read_csv('data/jan_2015.csv')
df15_2 = pd.read_csv('data/feb_2015.csv')
df15_3 = pd.read_csv('data/march_2015.csv')
df15_4 = pd.read_csv('data/april_2015.csv')
df15_5 = pd.read_csv('data/may_2015.csv')
df15_6 = pd.read_csv('data/june_2015.csv')
df15_7 = pd.read_csv('data/july_2015.csv')
df15_8 = pd.read_csv('data/aug_2015.csv')
df15_9 = pd.read_csv('data/sept_2015.csv')
df15_10 = pd.read_csv('data/oct_2015.csv')
df15_11 = pd.read_csv('data/nov_2015.csv')
df15_12 = pd.read_csv('data/dec_2015.csv')

In [52]:
# df15_12.head()

## Join the separate months into a full dataframe for all of 2018

In [53]:
df18 = pd.concat([df18_1, df18_2, df18_3, df18_4, df18_5, df18_6, df18_7, df18_8, df18_9], sort=True)
df18.head()

,ARR_DELAY,CARRIER_DELAY,DAY_OF_WEEK,DEP_DELAY,DEP_TIME,DEST,DEST_AIRPORT_ID,DEST_CITY_NAME,DEST_STATE_ABR,FL_DATE,...,NAS_DELAY,OP_UNIQUE_CARRIER,ORIGIN,ORIGIN_AIRPORT_ID,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,SECURITY_DELAY,TAIL_NUM,Unnamed: 20,WEATHER_DELAY
0,26.0,0.0,1,44.0,1400.0,SFO,14771,"San Francisco, CA",CA,2018-01-22,...,0.0,UA,LAS,12889,"Las Vegas, NV",NV,0.0,N37462,NaN,0.0
1,-13.0,NaN,1,-7.0,1328.0,DEN,11292,"Denver, CO",CO,2018-01-22,...,NaN,UA,SNA,14908,"Santa Ana, CA",CA,NaN,N14250,NaN,NaN
2,-4.0,NaN,1,-6.0,1609.0,ORD,13930,"Chicago, IL",IL,2018-01-22,...,NaN,UA,RSW,14635,"Fort Myers, FL",FL,NaN,N16217,NaN,NaN
3,-4.0,NaN,1,0.0,2103.0,LGA,12953,"New York, NY",NY,2018-01-22,...,NaN,UA,ORD,13930,"Chicago, IL",IL,NaN,N33284,NaN,NaN
4,-9.0,NaN,1,-8.0,727.0,LAS,12889,"Las Vegas, NV",NV,2018-01-22,...,NaN,UA,IAH,12266,"Houston, TX",TX,NaN,N12216,NaN,NaN

## Join all of 2017

In [54]:
df17 = pd.concat([df17_1, df17_2, df17_3, df17_4, df17_5, df17_6, df17_7, df17_8, df17_9, df17_10, df17_11, df17_12], sort=True)
df17

,ARR_DELAY,CARRIER_DELAY,DAY_OF_WEEK,DEP_DELAY,DEP_TIME,DEST,DEST_AIRPORT_ID,DEST_CITY_NAME,DEST_STATE_ABR,FL_DATE,...,NAS_DELAY,OP_UNIQUE_CARRIER,ORIGIN,ORIGIN_AIRPORT_ID,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,SECURITY_DELAY,TAIL_NUM,Unnamed: 20,WEATHER_DELAY
0,12.0,NaN,1,-3.0,757.0,LAX,12892,"Los Angeles, CA",CA,2017-01-02,...,NaN,AA,JFK,12478,"New York, NY",NY,NaN,N788AA,NaN,NaN
1,158.0,158.0,1,169.0,1049.0,LAX,12892,"Los Angeles, CA",CA,2017-01-09,...,0.0,AA,JFK,12478,"New York, NY",NY,0.0,N784AA,NaN,0.0
2,13.0,NaN,1,-2.0,758.0,LAX,12892,"Los Angeles, CA",CA,2017-01-16,...,NaN,AA,JFK,12478,"New York, NY",NY,NaN,N798AA,NaN,NaN
3,-5.0,NaN,1,-2.0,758.0,LAX,12892,"Los Angeles, CA",CA,2017-01-23,...,NaN,AA,JFK,12478,"New York, NY",NY,NaN,N798AA,NaN,NaN
4,-56.0,NaN,1,-10.0,750.0,LAX,12892,"Los Angeles, CA",CA,2017-01-30,...,NaN,AA,JFK,12478,"New York, NY",NY,NaN,N791AA,NaN,NaN
5,-3.0,NaN,1,-5.0,855.0,JFK,12478,"New York, NY",NY,2017-01-02,...,NaN,AA,LAX,12892,"Los Angeles, CA",CA,NaN,N796AA,NaN,NaN
6,25.0,0.0,1,-1.0,859.0,JFK,12478,"New York, NY",NY,2017-01-09,...,25.0,AA,LAX,12892,"Los Angeles, CA",CA,0.0,N799AA,NaN,0.0
7,-18.0,NaN,1,-1.0,859.0,JFK,12478,"New York, NY",NY,2017-01-16,...,NaN,AA,LAX,12892,"Los Angeles, CA",CA,NaN,N796AA,NaN,NaN
8,24.0,0.0,1,-7.0,853.0,JFK,12478,"New York, NY",NY,2017-01-23,...,24.0,AA,LAX,12892,"Los Angeles, CA",CA,0.0,N797AA,NaN,0.0
9,-12.0,NaN,1,-10.0,850.0,JFK,12478,"New York, NY",NY,2017-01-30,...,NaN,AA,LAX,12892,"Los Angeles, CA",CA,NaN,N798AA,NaN,NaN
10,4.0,NaN,1,10.0,1210.0,LAX,12892,"Los Angeles, CA",CA,2017-01-09,...,NaN,AA,JFK,12478,"New York, NY",NY,NaN,N788AA,NaN,NaN
11,-50.0,NaN,1,-9.0,1151.0,LAX,12892,"Los Angeles, CA",CA,2017-01-16,...,NaN,AA,JFK,12478,"New York, NY",NY,NaN,N788AA,NaN,NaN
12,16.0,0.0,1,-7.0,1153.0,LAX,12892,"Los Angeles, CA",CA,2017-01-23,...,16.0,AA,JFK,12478,"New York, NY",NY,0.0,N796AA,NaN,0.0
13,80.0,80.0,1,102.0,1342.0,LAX,12892,"Los Angeles, CA",CA,2017-01-30,...,0.0,AA,JFK,12478,"New York, NY",NY,0.0,N797AA,NaN,0.0
14,6.0,NaN,1,21.0,1151.0,JFK,12478,"New York, NY",NY,2017-01-02,...,NaN,AA,LAX,12892,"Los Angeles, CA",CA,NaN,N790AA,NaN,NaN
15,-9.0,NaN,1,11.0,1141.0,JFK,12478,"New York, NY",NY,2017-01-09,...,NaN,AA,LAX,12892,"Los Angeles, CA",CA,NaN,N783AA,NaN,NaN
16,-29.0,NaN,1,-3.0,1127.0,JFK,12478,"New York, NY",NY,2017-01-16,...,NaN,AA,LAX,12892,"Los Angeles, CA",CA,NaN,N793AA,NaN,NaN
17,177.0,0.0,1,196.0,1446.0,JFK,12478,"New York, NY",NY,2017-01-23,...,0.0,AA,LAX,12892,"Los Angeles, CA",CA,0.0,N789AA,NaN,0.0
18,-29.0,NaN,1,-2.0,1128.0,JFK,12478,"New York, NY",NY,2017-01-30,...,NaN,AA,LAX,12892,"Los Angeles, CA",CA,NaN,N789AA,NaN,NaN
19,21.0,1.0,1,1.0,1136.0,HNL,12173,"Honolulu, HI",HI,2017-01-02,...,20.0,AA,DFW,11298,"Dallas/Fort Worth, TX",TX,0.0,N399AA,NaN,0.0
20,259.0,236.0,1,236.0,1506.0,HNL,12173,"Honolulu, HI",HI,2017-01-09,...,23.0,AA,DFW,11298,"Dallas/Fort Worth, TX",TX,0.0,N388AA,NaN,0.0
21,-45.0,NaN,1,5.0,1115.0,HNL,12173,"Honolulu, HI",HI,2017-01-16,...,NaN,AA,DFW,11298,"Dallas/Fort Worth, TX",TX,NaN,N393AA,NaN,NaN
22,24.0,0.0,1,-5.0,1105.0,HNL,12173,"Honolulu, HI",HI,2017-01-23,...,24.0,AA,DFW,11298,"Dallas/Fort Worth, TX",TX,0.0,N381AA,NaN,0.0
23,-8.0,NaN,1,3.0,1113.0,HNL,12173,"Honolulu, HI",HI,2017-01-30,...,NaN,AA,DFW,11298,"Dallas/Fort Worth, TX",TX,NaN,N347AA,NaN,NaN
24,52.0,0.0,1,-7.0,503.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2017-01-02,...,52.0,AA,OKC,13851,"Oklahoma City, OK",OK,0.0,N4XBAA,NaN,0.0
25,3.0,NaN,1,-5.0,505.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2017-01-09,...,NaN,AA,OKC,13851,"Oklahoma City, OK",OK,NaN,N4XJAA,NaN,NaN
26,91.0,0.0,1,86.0,636.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2017-01-16,...,5.0,AA,OKC,13851,"Oklahoma City, OK",OK,0.0,N4XCAA,NaN,86.0
27,-4.0,NaN,1,-7.0,503.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2017-01-23,...,NaN,AA,OKC,13851,"Oklahoma City, OK",OK,NaN,N425AA,NaN,NaN
28,-3.0,NaN,1,-12.0,458.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2017-01-30,...,NaN,AA,OKC,13851,"Oklahoma City, OK",OK,NaN,N4YPAA,NaN,NaN
29,-33.0,NaN,1,13.0,1908.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2017-01-02,...,NaN,AA,OGG,13830,"Kahului, HI",HI,NaN,N377AA,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464175,51.0,0.0,7,44.0,1504.0,PHL,14100,"Philadelphia, PA",PA,2017-12-10,...,7.0,AA,SJU,14843,"San Juan, PR",PR,0.0,N271AA,NaN,0.0
464176,-14.0,NaN,7,-12.0,1408.0,PHL,14100,"Philadelphia, PA",PA,2017-12-17,...,NaN,AA,SJU,14843,"San Juan, PR",PR,NaN,N279AA,NaN,NaN
464177,12.0,NaN,7,10.0,1430.0,PHL,14100,"Philadelphia, PA",PA,2017-12-24,...,NaN,AA,SJU,14843,"San Juan, PR",PR,NaN,N293AA,NaN,NaN
464178,-14.0,NaN,7,-11.0,1409.0,PHL,14100,"Philadelphia, PA",PA,2017-12-31,...,NaN,AA,SJU,14843,"San Juan, PR",PR,NaN,N292AA,NaN,NaN
464179,0.0,NaN,7,-3.0,1607.0,LGA,12953,"New York, NY",NY,2017-12-03,...,NaN,AA,CLT,11057,"Charlotte, NC",NC,NaN,N710AA,NaN,NaN
464180,-17.0,NaN,7,-3.0,1607.0,LGA,12953,"New York, NY",NY,2017-12-10,...,NaN,AA,CLT,11057,"Charlotte, NC",NC,NaN,N713AA,NaN,NaN
464181,8.0,NaN,7,4.0,1614.0,LGA,12953,"New York, NY",NY,2017-12-17,...,NaN,AA,CLT,11057,"Charlotte, NC",NC,NaN,N583AA,NaN,NaN
464182,-18.0,NaN,7,-2.0,1608.0,LGA,12953,"New York, NY",NY,2017-12-24,...,NaN,AA,CLT,11057,"Charlotte, NC",NC,NaN,N837AA,NaN,NaN
464183,-11.0,NaN,7,-2.0,1608.0,LGA,12953,"New York, NY",NY,2017-12-31,...,NaN,AA,CLT,11057,"Charlotte, NC",NC,NaN,N838AA,NaN,NaN
464184,-2.0,NaN,7,-2.0,1248.0,BOS,10721,"Boston, MA",MA,2017-12-03,...,NaN,AA,PHL,14100,"Philadelphia, PA",PA,NaN,N982AA,NaN,NaN
464185,-10.0,NaN,7,-3.0,1247.0,BOS,10721,"Boston, MA",MA,2017-12-10,...,NaN,AA,PHL,14100,"Philadelphia, PA",PA,NaN,N162AA,NaN,NaN
464186,-13.0,NaN,7,-4.0,1251.0,BOS,10721,"Boston, MA",MA,2017-12-17,...,NaN,AA,PHL,14100,"Philadelphia, PA",PA,NaN,N194AA,NaN,NaN
464187,87.0,5.0,7,111.0,1446.0,BOS,10721,"Boston, MA",MA,2017-12-24,...,0.0,AA,PHL,14100,"Philadelphia, PA",PA,0.0,N190AA,NaN,0.0
464188,-16.0,NaN,7,-6.0,1249.0,BOS,10721,"Boston, MA",MA,2017-12-31,...,NaN,AA,PHL,14100,"Philadelphia, PA",PA,NaN,N663AA,NaN,NaN
464189,11.0,NaN,7,6.0,2000.0,PWM,14321,"Portland, ME",ME,2017-12-03,...,NaN,AA,CLT,11057,"Charlotte, NC",NC,NaN,N700AA,NaN,NaN
464190,-1.0,NaN,7,13.0,2007.0,PWM,14321,"Portland, ME",ME,2017-12-10,...,NaN,AA,CLT,11057,"Charlotte, NC",NC,NaN,N721AA,NaN,NaN
464191,-5.0,NaN,7,-3.0,2027.0,PWM,14321,"Portland, ME",ME,2017-12-17,...,NaN,AA,CLT,11057,"Charlotte, NC",NC,NaN,N535AA,NaN,NaN
464192,-27.0,NaN,7,-2.0,2028.0,PWM,14321,"Portland, ME",ME,2017-12-24,...,NaN,AA,CLT,11057,"Charlotte, NC",NC,NaN,N184AA,NaN,NaN
464193,22.0,3.0,7,4.0,2034.0,PWM,14321,"Portland, ME",ME,2017-12-31,...,18.0,AA,CLT,11057,"Charlotte, NC",NC,0.0,N914AA,NaN,0.0
464194,6.0,NaN,7,6.0,1132.0,CLT,11057,"Charlotte, NC",NC,2017-12-17,...,NaN,AA,LAX,12892,"Los Angeles, CA",CA,NaN,N535AA,NaN,NaN
464195,98.0,98.0,7,135.0,1341.0,CLT,11057,"Charlotte, NC",NC,2017-12-24,...,0.0,AA,LAX,12892,"Los Angeles, CA",CA,0.0,N194AA,NaN,0.0
464196,-23.0,NaN,7,-7.0,1119.0,CLT,11057,"Charlotte, NC",NC,2017-12-31,...,NaN,AA,LAX,12892,"Los Angeles, CA",CA,NaN,N152AA,NaN,NaN
464197,12.0,NaN,7,16.0,1136.0,TPA,15304,"Tampa, FL",FL,2017-12-03,...,NaN,AA,CLT,11057,"Charlotte, NC",NC,NaN,N549AA,NaN,NaN
464198,93.0,61.0,7,84.0,1244.0,TPA,15304,"Tampa, FL",FL,2017-12-10,...,9.0,AA,CLT,11057,"Charlotte, NC",NC,0.0,N5EYAA,NaN,0.0
464199,-16.0,NaN,7,-3.0,1117.0,TPA,15304,"Tampa, FL",FL,2017-12-17,...,NaN,AA,CLT,11057,"Charlotte, NC",NC,NaN,N103AA,NaN,NaN
464200,-10.0,NaN,7,-4.0,1116.0,TPA,15304,"Tampa, FL",FL,2017-12-24,...,NaN,AA,CLT,11057,"Charlotte, NC",NC,NaN,N107AA,NaN,NaN
464201,-19.0,NaN,7,-6.0,1114.0,TPA,15304,"Tampa, FL",FL,2017-12-31,...,NaN,AA,CLT,11057,"Charlotte, NC",NC,NaN,N126AA,NaN,NaN
464202,0.0,NaN,7,9.0,1359.0,CLT,11057,"Charlotte, NC",NC,2017-12-03,...,NaN,AA,TPA,15304,"Tampa, FL",FL,NaN,N549AA,NaN,NaN
464203,107.0,12.0,7,105.0,1535.0,CLT,11057,"Charlotte, NC",NC,2017-12-10,...,2.0,AA,TPA,15304,"Tampa, FL",FL,0.0,N5EYAA,NaN,0.0
464204,-9.0,NaN,7,-6.0,1344.0,CLT,11057,"Charlotte, NC",NC,2017-12-17,...,NaN,AA,TPA,15304,"Tampa, FL",FL,NaN,N103AA,NaN,NaN

## Now let's join 2016

In [55]:
df16 = pd.concat([df16_1, df16_2, df16_3, df16_4, df16_5, df16_6, df16_7, df16_8, df16_9, df16_10, df16_11, df16_12], sort=True)
df16

,ARR_DELAY,CARRIER_DELAY,DAY_OF_WEEK,DEP_DELAY,DEP_TIME,DEST,DEST_AIRPORT_ID,DEST_CITY_NAME,DEST_STATE_ABR,FL_DATE,...,NAS_DELAY,OP_UNIQUE_CARRIER,ORIGIN,ORIGIN_AIRPORT_ID,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,SECURITY_DELAY,TAIL_NUM,Unnamed: 20,WEATHER_DELAY
0,-2.0,NaN,1,-2.0,728.0,FLL,11697,"Fort Lauderdale, FL",FL,2016-01-04,...,NaN,DL,MSP,13487,"Minneapolis, MN",MN,NaN,N663DN,NaN,NaN
1,-11.0,NaN,1,3.0,1323.0,MSP,13487,"Minneapolis, MN",MN,2016-01-04,...,NaN,DL,FLL,11697,"Fort Lauderdale, FL",FL,NaN,N663DN,NaN,NaN
2,5.0,NaN,1,-1.0,559.0,DTW,11433,"Detroit, MI",MI,2016-01-04,...,NaN,DL,BDL,10529,"Hartford, CT",CT,NaN,N954DL,NaN,NaN
3,-13.0,NaN,1,-2.0,558.0,ATL,10397,"Atlanta, GA",GA,2016-01-04,...,NaN,DL,LIT,12992,"Little Rock, AR",AR,NaN,N991DL,NaN,NaN
4,1.0,NaN,1,18.0,743.0,ATL,10397,"Atlanta, GA",GA,2016-01-04,...,NaN,DL,RDU,14492,"Raleigh/Durham, NC",NC,NaN,N915DE,NaN,NaN
5,-5.0,NaN,1,-6.0,829.0,LAS,12889,"Las Vegas, NV",NV,2016-01-04,...,NaN,DL,SLC,14869,"Salt Lake City, UT",UT,NaN,N3758Y,NaN,NaN
6,-29.0,NaN,1,-2.0,1123.0,GEG,11884,"Spokane, WA",WA,2016-01-04,...,NaN,DL,MSP,13487,"Minneapolis, MN",MN,NaN,N924DN,NaN,NaN
7,6.0,NaN,1,-3.0,1322.0,MSP,13487,"Minneapolis, MN",MN,2016-01-04,...,NaN,DL,GEG,11884,"Spokane, WA",WA,NaN,N924DN,NaN,NaN
8,-7.0,NaN,1,-4.0,1946.0,MCO,13204,"Orlando, FL",FL,2016-01-04,...,NaN,DL,LGA,12953,"New York, NY",NY,NaN,N961DL,NaN,NaN
9,5.0,NaN,1,25.0,1310.0,LGA,12953,"New York, NY",NY,2016-01-04,...,NaN,DL,ATL,10397,"Atlanta, GA",GA,NaN,N915DL,NaN,NaN
10,-11.0,NaN,1,1.0,816.0,MCO,13204,"Orlando, FL",FL,2016-01-04,...,NaN,DL,LGA,12953,"New York, NY",NY,NaN,N969DL,NaN,NaN
11,-15.0,NaN,1,4.0,1344.0,IAH,12266,"Houston, TX",TX,2016-01-04,...,NaN,DL,ATL,10397,"Atlanta, GA",GA,NaN,N603AT,NaN,NaN
12,-11.0,NaN,1,-5.0,1531.0,ATL,10397,"Atlanta, GA",GA,2016-01-04,...,NaN,DL,IAH,12266,"Houston, TX",TX,NaN,N603AT,NaN,NaN
13,-12.0,NaN,1,0.0,1547.0,LAS,12889,"Las Vegas, NV",NV,2016-01-04,...,NaN,DL,DTW,11433,"Detroit, MI",MI,NaN,N594NW,NaN,NaN
14,-24.0,NaN,1,-8.0,602.0,ATL,10397,"Atlanta, GA",GA,2016-01-04,...,NaN,DL,MSP,13487,"Minneapolis, MN",MN,NaN,N825DN,NaN,NaN
15,-8.0,NaN,1,0.0,805.0,MSP,13487,"Minneapolis, MN",MN,2016-01-04,...,NaN,DL,PHX,14107,"Phoenix, AZ",AZ,NaN,N915DN,NaN,NaN
16,36.0,36.0,1,44.0,1044.0,DTW,11433,"Detroit, MI",MI,2016-01-04,...,0.0,DL,FLL,11697,"Fort Lauderdale, FL",FL,0.0,N699DL,NaN,0.0
17,-7.0,NaN,1,-1.0,844.0,PHL,14100,"Philadelphia, PA",PA,2016-01-04,...,NaN,DL,ATL,10397,"Atlanta, GA",GA,NaN,N938DL,NaN,NaN
18,-34.0,NaN,1,-5.0,1125.0,ATL,10397,"Atlanta, GA",GA,2016-01-04,...,NaN,DL,PHL,14100,"Philadelphia, PA",PA,NaN,N938DL,NaN,NaN
19,-4.0,NaN,1,-1.0,1115.0,BWI,10821,"Baltimore, MD",MD,2016-01-04,...,NaN,DL,ATL,10397,"Atlanta, GA",GA,NaN,N987DL,NaN,NaN
20,-26.0,NaN,1,-2.0,1343.0,ATL,10397,"Atlanta, GA",GA,2016-01-04,...,NaN,DL,BWI,10821,"Baltimore, MD",MD,NaN,N987DL,NaN,NaN
21,-10.0,NaN,1,-1.0,1307.0,LGA,12953,"New York, NY",NY,2016-01-04,...,NaN,DL,MSP,13487,"Minneapolis, MN",MN,NaN,N924DL,NaN,NaN
22,-22.0,NaN,1,-3.0,832.0,MSP,13487,"Minneapolis, MN",MN,2016-01-04,...,NaN,DL,PHL,14100,"Philadelphia, PA",PA,NaN,N921DN,NaN,NaN
23,-24.0,NaN,1,-2.0,700.0,LGA,12953,"New York, NY",NY,2016-01-04,...,NaN,DL,FLL,11697,"Fort Lauderdale, FL",FL,NaN,N965AT,NaN,NaN
24,-9.0,NaN,1,-3.0,602.0,ATL,10397,"Atlanta, GA",GA,2016-01-04,...,NaN,DL,MEM,13244,"Memphis, TN",TN,NaN,N920DE,NaN,NaN
25,9.0,NaN,1,10.0,1400.0,BOS,10721,"Boston, MA",MA,2016-01-04,...,NaN,DL,ATL,10397,"Atlanta, GA",GA,NaN,N904DE,NaN,NaN
26,-26.0,NaN,1,-1.0,714.0,ATL,10397,"Atlanta, GA",GA,2016-01-04,...,NaN,DL,BOS,10721,"Boston, MA",MA,NaN,N814DN,NaN,NaN
27,-36.0,NaN,1,-11.0,1319.0,ATL,10397,"Atlanta, GA",GA,2016-01-04,...,NaN,DL,GRR,11986,"Grand Rapids, MI",MI,NaN,N947AT,NaN,NaN
28,-8.0,NaN,1,-4.0,1956.0,PVD,14307,"Providence, RI",RI,2016-01-04,...,NaN,DL,ATL,10397,"Atlanta, GA",GA,NaN,N976DL,NaN,NaN
29,107.0,0.0,1,86.0,826.0,JFK,12478,"New York, NY",NY,2016-01-04,...,21.0,DL,PDX,14057,"Portland, OR",OR,0.0,N398DA,NaN,86.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460919,10.0,NaN,7,14.0,710.0,LAS,12889,"Las Vegas, NV",NV,2016-12-18,...,NaN,NK,DTW,11433,"Detroit, MI",MI,NaN,N605NK,NaN,NaN
460920,-5.0,NaN,7,-4.0,652.0,LAS,12889,"Las Vegas, NV",NV,2016-12-25,...,NaN,NK,DTW,11433,"Detroit, MI",MI,NaN,N636NK,NaN,NaN
460921,-8.0,NaN,7,-5.0,814.0,SAN,14679,"San Diego, CA",CA,2016-12-04,...,NaN,NK,LAS,12889,"Las Vegas, NV",NV,NaN,N614NK,NaN,NaN
460922,43.0,0.0,7,46.0,905.0,SAN,14679,"San Diego, CA",CA,2016-12-11,...,43.0,NK,LAS,12889,"Las Vegas, NV",NV,0.0,N628NK,NaN,0.0
460923,9.0,NaN,7,9.0,922.0,SAN,14679,"San Diego, CA",CA,2016-12-18,...,NaN,NK,LAS,12889,"Las Vegas, NV",NV,NaN,N605NK,NaN,NaN
460924,8.0,NaN,7,14.0,927.0,SAN,14679,"San Diego, CA",CA,2016-12-25,...,NaN,NK,LAS,12889,"Las Vegas, NV",NV,NaN,N636NK,NaN,NaN
460925,-20.0,NaN,7,0.0,630.0,BWI,10821,"Baltimore, MD",MD,2016-12-04,...,NaN,NK,IAH,12266,"Houston, TX",TX,NaN,N606NK,NaN,NaN
460926,-4.0,NaN,7,-6.0,624.0,BWI,10821,"Baltimore, MD",MD,2016-12-11,...,NaN,NK,IAH,12266,"Houston, TX",TX,NaN,N643NK,NaN,NaN
460927,12.0,NaN,7,12.0,627.0,BWI,10821,"Baltimore, MD",MD,2016-12-18,...,NaN,NK,IAH,12266,"Houston, TX",TX,NaN,N633NK,NaN,NaN
460928,80.0,80.0,7,81.0,736.0,BWI,10821,"Baltimore, MD",MD,2016-12-25,...,0.0,NK,IAH,12266,"Houston, TX",TX,0.0,N632NK,NaN,0.0
460929,97.0,4.0,7,82.0,2232.0,IAH,12266,"Houston, TX",TX,2016-12-04,...,93.0,NK,BWI,10821,"Baltimore, MD",MD,0.0,N644NK,NaN,0.0
460930,2.0,NaN,7,20.0,2130.0,IAH,12266,"Houston, TX",TX,2016-12-11,...,NaN,NK,BWI,10821,"Baltimore, MD",MD,NaN,N643NK,NaN,NaN
460931,185.0,16.0,7,179.0,7.0,IAH,12266,"Houston, TX",TX,2016-12-18,...,6.0,NK,BWI,10821,"Baltimore, MD",MD,0.0,N632NK,NaN,0.0
460932,NaN,NaN,7,-11.0,2057.0,IAH,12266,"Houston, TX",TX,2016-12-25,...,NaN,NK,BWI,10821,"Baltimore, MD",MD,NaN,N604NK,NaN,NaN
460933,42.0,0.0,7,-9.0,1901.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2016-12-04,...,42.0,NK,FLL,11697,"Fort Lauderdale, FL",FL,0.0,N522NK,NaN,0.0
460934,-9.0,NaN,7,2.0,1912.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2016-12-11,...,NaN,NK,FLL,11697,"Fort Lauderdale, FL",FL,NaN,N503NK,NaN,NaN
460935,4.0,NaN,7,13.0,1900.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2016-12-18,...,NaN,NK,FLL,11697,"Fort Lauderdale, FL",FL,NaN,N522NK,NaN,NaN
460936,-30.0,NaN,7,-3.0,1844.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2016-12-25,...,NaN,NK,FLL,11697,"Fort Lauderdale, FL",FL,NaN,N534NK,NaN,NaN
460937,-18.0,NaN,7,-9.0,651.0,RSW,14635,"Fort Myers, FL",FL,2016-12-04,...,NaN,NK,ORD,13930,"Chicago, IL",IL,NaN,N668NK,NaN,NaN
460938,NaN,NaN,7,NaN,NaN,RSW,14635,"Fort Myers, FL",FL,2016-12-11,...,NaN,NK,ORD,13930,"Chicago, IL",IL,NaN,N669NK,NaN,NaN
460939,37.0,0.0,7,27.0,727.0,RSW,14635,"Fort Myers, FL",FL,2016-12-18,...,10.0,NK,ORD,13930,"Chicago, IL",IL,0.0,N668NK,NaN,27.0
460940,-11.0,NaN,7,-3.0,657.0,RSW,14635,"Fort Myers, FL",FL,2016-12-25,...,NaN,NK,ORD,13930,"Chicago, IL",IL,NaN,N668NK,NaN,NaN
460941,156.0,0.0,7,152.0,1937.0,ORD,13930,"Chicago, IL",IL,2016-12-04,...,156.0,NK,RSW,14635,"Fort Myers, FL",FL,0.0,N637NK,NaN,0.0
460942,90.0,0.0,7,88.0,1833.0,ORD,13930,"Chicago, IL",IL,2016-12-11,...,90.0,NK,RSW,14635,"Fort Myers, FL",FL,0.0,N638NK,NaN,0.0
460943,-30.0,NaN,7,-12.0,1652.0,ORD,13930,"Chicago, IL",IL,2016-12-18,...,NaN,NK,RSW,14635,"Fort Myers, FL",FL,NaN,N643NK,NaN,NaN
460944,-25.0,NaN,7,-13.0,1651.0,ORD,13930,"Chicago, IL",IL,2016-12-25,...,NaN,NK,RSW,14635,"Fort Myers, FL",FL,NaN,N624NK,NaN,NaN
460945,39.0,32.0,7,40.0,2045.0,MYR,13577,"Myrtle Beach, SC",SC,2016-12-04,...,7.0,NK,FLL,11697,"Fort Lauderdale, FL",FL,0.0,N525NK,NaN,0.0
460946,-2.0,NaN,7,3.0,2008.0,MYR,13577,"Myrtle Beach, SC",SC,2016-12-11,...,NaN,NK,FLL,11697,"Fort Lauderdale, FL",FL,NaN,N534NK,NaN,NaN
460947,152.0,102.0,7,156.0,2251.0,MYR,13577,"Myrtle Beach, SC",SC,2016-12-18,...,1.0,NK,FLL,11697,"Fort Lauderdale, FL",FL,0.0,N524NK,NaN,0.0
460948,-23.0,NaN,7,-10.0,2005.0,MYR,13577,"Myrtle Beach, SC",SC,2016-12-25,...,NaN,NK,FLL,11697,"Fort Lauderdale, FL",FL,NaN,N515NK,NaN,NaN

## And finally, 2015

In [56]:
df15 = pd.concat([df15_1, df15_2, df15_3, df15_4, df15_5, df15_6, df15_7, df15_8, df15_9, df15_10, df15_11, df15_12], sort=True)
df15

,ARR_DELAY,CARRIER_DELAY,DAY_OF_WEEK,DEP_DELAY,DEP_TIME,DEST,DEST_AIRPORT_ID,DEST_CITY_NAME,DEST_STATE_ABR,FL_DATE,...,NAS_DELAY,OP_UNIQUE_CARRIER,ORIGIN,ORIGIN_AIRPORT_ID,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,SECURITY_DELAY,TAIL_NUM,Unnamed: 20,WEATHER_DELAY
0,-11.0,NaN,1,8.0,708.0,LAS,12889,"Las Vegas, NV",NV,2015-01-05,...,NaN,NK,IAH,12266,"Houston, TX",TX,NaN,N523NK,NaN,NaN
1,22.0,22.0,1,22.0,722.0,LAS,12889,"Las Vegas, NV",NV,2015-01-12,...,0.0,NK,IAH,12266,"Houston, TX",TX,0.0,N525NK,NaN,0.0
2,-12.0,NaN,1,-6.0,654.0,LAS,12889,"Las Vegas, NV",NV,2015-01-19,...,NaN,NK,IAH,12266,"Houston, TX",TX,NaN,N533NK,NaN,NaN
3,-16.0,NaN,1,-6.0,654.0,LAS,12889,"Las Vegas, NV",NV,2015-01-26,...,NaN,NK,IAH,12266,"Houston, TX",TX,NaN,N506NK,NaN,NaN
4,-4.0,NaN,1,1.0,2149.0,FLL,11697,"Fort Lauderdale, FL",FL,2015-01-05,...,NaN,NK,MCO,13204,"Orlando, FL",FL,NaN,N608NK,NaN,NaN
5,10.0,NaN,1,9.0,2157.0,FLL,11697,"Fort Lauderdale, FL",FL,2015-01-12,...,NaN,NK,MCO,13204,"Orlando, FL",FL,NaN,N605NK,NaN,NaN
6,-13.0,NaN,1,-10.0,2138.0,FLL,11697,"Fort Lauderdale, FL",FL,2015-01-19,...,NaN,NK,MCO,13204,"Orlando, FL",FL,NaN,N629NK,NaN,NaN
7,1.0,NaN,1,-2.0,2146.0,FLL,11697,"Fort Lauderdale, FL",FL,2015-01-26,...,NaN,NK,MCO,13204,"Orlando, FL",FL,NaN,N626NK,NaN,NaN
8,8.0,NaN,1,5.0,1055.0,FLL,11697,"Fort Lauderdale, FL",FL,2015-01-05,...,NaN,NK,LGA,12953,"New York, NY",NY,NaN,N613NK,NaN,NaN
9,14.0,NaN,1,26.0,1116.0,FLL,11697,"Fort Lauderdale, FL",FL,2015-01-12,...,NaN,NK,LGA,12953,"New York, NY",NY,NaN,N625NK,NaN,NaN
10,-35.0,NaN,1,0.0,1050.0,FLL,11697,"Fort Lauderdale, FL",FL,2015-01-19,...,NaN,NK,LGA,12953,"New York, NY",NY,NaN,N616NK,NaN,NaN
11,97.0,59.0,1,59.0,1149.0,FLL,11697,"Fort Lauderdale, FL",FL,2015-01-26,...,38.0,NK,LGA,12953,"New York, NY",NY,0.0,N620NK,NaN,0.0
12,17.0,0.0,1,18.0,718.0,MCO,13204,"Orlando, FL",FL,2015-01-05,...,17.0,NK,FLL,11697,"Fort Lauderdale, FL",FL,0.0,N605NK,NaN,0.0
13,-8.0,NaN,1,-5.0,655.0,MCO,13204,"Orlando, FL",FL,2015-01-12,...,NaN,NK,FLL,11697,"Fort Lauderdale, FL",FL,NaN,N622NK,NaN,NaN
14,9.0,NaN,1,10.0,710.0,MCO,13204,"Orlando, FL",FL,2015-01-19,...,NaN,NK,FLL,11697,"Fort Lauderdale, FL",FL,NaN,N630NK,NaN,NaN
15,-4.0,NaN,1,-7.0,653.0,MCO,13204,"Orlando, FL",FL,2015-01-26,...,NaN,NK,FLL,11697,"Fort Lauderdale, FL",FL,NaN,N613NK,NaN,NaN
16,0.0,NaN,1,15.0,2255.0,LAS,12889,"Las Vegas, NV",NV,2015-01-05,...,NaN,NK,IAH,12266,"Houston, TX",TX,NaN,N523NK,NaN,NaN
17,9.0,NaN,1,-8.0,2232.0,LAS,12889,"Las Vegas, NV",NV,2015-01-12,...,NaN,NK,IAH,12266,"Houston, TX",TX,NaN,N525NK,NaN,NaN
18,-7.0,NaN,1,-9.0,2231.0,LAS,12889,"Las Vegas, NV",NV,2015-01-19,...,NaN,NK,IAH,12266,"Houston, TX",TX,NaN,N533NK,NaN,NaN
19,-19.0,NaN,1,1.0,2241.0,LAS,12889,"Las Vegas, NV",NV,2015-01-26,...,NaN,NK,IAH,12266,"Houston, TX",TX,NaN,N506NK,NaN,NaN
20,39.0,0.0,1,39.0,654.0,ORD,13930,"Chicago, IL",IL,2015-01-05,...,39.0,NK,IAH,12266,"Houston, TX",TX,0.0,N510NK,NaN,0.0
21,-1.0,NaN,1,-7.0,608.0,ORD,13930,"Chicago, IL",IL,2015-01-12,...,NaN,NK,IAH,12266,"Houston, TX",TX,NaN,N505NK,NaN,NaN
22,-11.0,NaN,1,-4.0,611.0,ORD,13930,"Chicago, IL",IL,2015-01-19,...,NaN,NK,IAH,12266,"Houston, TX",TX,NaN,N507NK,NaN,NaN
23,9.0,NaN,1,-10.0,605.0,ORD,13930,"Chicago, IL",IL,2015-01-26,...,NaN,NK,IAH,12266,"Houston, TX",TX,NaN,N503NK,NaN,NaN
24,NaN,NaN,1,90.0,1419.0,STT,15024,"Charlotte Amalie, VI",VI,2015-01-05,...,NaN,NK,FLL,11697,"Fort Lauderdale, FL",FL,NaN,N532NK,NaN,NaN
25,-3.0,NaN,1,5.0,1254.0,STT,15024,"Charlotte Amalie, VI",VI,2015-01-12,...,NaN,NK,FLL,11697,"Fort Lauderdale, FL",FL,NaN,N504NK,NaN,NaN
26,-19.0,NaN,1,0.0,1249.0,STT,15024,"Charlotte Amalie, VI",VI,2015-01-19,...,NaN,NK,FLL,11697,"Fort Lauderdale, FL",FL,NaN,N512NK,NaN,NaN
27,31.0,4.0,1,22.0,1311.0,STT,15024,"Charlotte Amalie, VI",VI,2015-01-26,...,27.0,NK,FLL,11697,"Fort Lauderdale, FL",FL,0.0,N504NK,NaN,0.0
28,-22.0,NaN,1,-8.0,1338.0,BWI,10821,"Baltimore, MD",MD,2015-01-05,...,NaN,NK,DFW,11298,"Dallas/Fort Worth, TX",TX,NaN,N631NK,NaN,NaN
29,-1.0,NaN,1,1.0,1347.0,BWI,10821,"Baltimore, MD",MD,2015-01-12,...,NaN,NK,DFW,11298,"Dallas/Fort Worth, TX",TX,NaN,N623NK,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479200,-10.0,NaN,7,-2.0,2208.0,AZO,10469,"Kalamazoo, MI",MI,2015-12-27,...,NaN,MQ,ORD,13930,"Chicago, IL",IL,NaN,N809MQ,NaN,NaN
479201,5.0,NaN,7,10.0,2145.0,CVG,11193,"Cincinnati, OH",KY,2015-12-06,...,NaN,MQ,ORD,13930,"Chicago, IL",IL,NaN,N657MQ,NaN,NaN
479202,-4.0,NaN,7,1.0,2136.0,CVG,11193,"Cincinnati, OH",KY,2015-12-13,...,NaN,MQ,ORD,13930,"Chicago, IL",IL,NaN,N923MQ,NaN,NaN
479203,-16.0,NaN,7,-5.0,2133.0,CVG,11193,"Cincinnati, OH",KY,2015-12-20,...,NaN,MQ,ORD,13930,"Chicago, IL",IL,NaN,N925MQ,NaN,NaN
479204,2.0,NaN,7,1.0,2139.0,CVG,11193,"Cincinnati, OH",KY,2015-12-27,...,NaN,MQ,ORD,13930,"Chicago, IL",IL,NaN,N643MQ,NaN,NaN
479205,-14.0,NaN,7,-3.0,1346.0,ORD,13930,"Chicago, IL",IL,2015-12-06,...,NaN,MQ,ABQ,10140,"Albuquerque, NM",NM,NaN,N525MQ,NaN,NaN
479206,-5.0,NaN,7,-6.0,1343.0,ORD,13930,"Chicago, IL",IL,2015-12-13,...,NaN,MQ,ABQ,10140,"Albuquerque, NM",NM,NaN,N1EAMQ,NaN,NaN
479207,-11.0,NaN,7,-4.0,1336.0,ORD,13930,"Chicago, IL",IL,2015-12-20,...,NaN,MQ,ABQ,10140,"Albuquerque, NM",NM,NaN,N531MQ,NaN,NaN
479208,13.0,NaN,7,8.0,1348.0,ORD,13930,"Chicago, IL",IL,2015-12-27,...,NaN,MQ,ABQ,10140,"Albuquerque, NM",NM,NaN,N9EAMQ,NaN,NaN
479209,-21.0,NaN,7,-5.0,1105.0,ABQ,10140,"Albuquerque, NM",NM,2015-12-06,...,NaN,MQ,ORD,13930,"Chicago, IL",IL,NaN,N525MQ,NaN,NaN
479210,-19.0,NaN,7,-1.0,1109.0,ABQ,10140,"Albuquerque, NM",NM,2015-12-13,...,NaN,MQ,ORD,13930,"Chicago, IL",IL,NaN,N1EAMQ,NaN,NaN
479211,-3.0,NaN,7,-1.0,1014.0,ABQ,10140,"Albuquerque, NM",NM,2015-12-20,...,NaN,MQ,ORD,13930,"Chicago, IL",IL,NaN,N531MQ,NaN,NaN
479212,21.0,14.0,7,14.0,1029.0,ABQ,10140,"Albuquerque, NM",NM,2015-12-27,...,7.0,MQ,ORD,13930,"Chicago, IL",IL,0.0,N9EAMQ,NaN,0.0
479213,-8.0,NaN,7,-5.0,1205.0,LCH,12915,"Lake Charles, LA",LA,2015-12-06,...,NaN,MQ,DFW,11298,"Dallas/Fort Worth, TX",TX,NaN,N922MQ,NaN,NaN
479214,17.0,0.0,7,0.0,1210.0,LCH,12915,"Lake Charles, LA",LA,2015-12-13,...,17.0,MQ,DFW,11298,"Dallas/Fort Worth, TX",TX,0.0,N653MQ,NaN,0.0
479215,3.0,NaN,7,5.0,1215.0,LCH,12915,"Lake Charles, LA",LA,2015-12-20,...,NaN,MQ,DFW,11298,"Dallas/Fort Worth, TX",TX,NaN,N695MQ,NaN,NaN
479216,40.0,0.0,7,18.0,1228.0,LCH,12915,"Lake Charles, LA",LA,2015-12-27,...,22.0,MQ,DFW,11298,"Dallas/Fort Worth, TX",TX,0.0,N648MQ,NaN,0.0
479217,-22.0,NaN,7,-6.0,1352.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2015-12-06,...,NaN,MQ,LCH,12915,"Lake Charles, LA",LA,NaN,N922MQ,NaN,NaN
479218,-4.0,NaN,7,12.0,1410.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2015-12-13,...,NaN,MQ,LCH,12915,"Lake Charles, LA",LA,NaN,N653MQ,NaN,NaN
479219,-2.0,NaN,7,-1.0,1357.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2015-12-20,...,NaN,MQ,LCH,12915,"Lake Charles, LA",LA,NaN,N695MQ,NaN,NaN
479220,259.0,0.0,7,203.0,1721.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2015-12-27,...,56.0,MQ,LCH,12915,"Lake Charles, LA",LA,0.0,N648MQ,NaN,168.0
479221,-5.0,NaN,7,-2.0,1828.0,FAR,11637,"Fargo, ND",ND,2015-12-06,...,NaN,MQ,DFW,11298,"Dallas/Fort Worth, TX",TX,NaN,N918MQ,NaN,NaN
479222,-38.0,NaN,7,-4.0,1826.0,FAR,11637,"Fargo, ND",ND,2015-12-13,...,NaN,MQ,DFW,11298,"Dallas/Fort Worth, TX",TX,NaN,N922MQ,NaN,NaN
479223,-36.0,NaN,7,-3.0,1827.0,FAR,11637,"Fargo, ND",ND,2015-12-20,...,NaN,MQ,DFW,11298,"Dallas/Fort Worth, TX",TX,NaN,N928MQ,NaN,NaN
479224,NaN,NaN,7,NaN,NaN,FAR,11637,"Fargo, ND",ND,2015-12-27,...,NaN,MQ,DFW,11298,"Dallas/Fort Worth, TX",TX,NaN,N931MQ,NaN,NaN
479225,-9.0,NaN,7,7.0,637.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2015-12-06,...,NaN,MQ,LCH,12915,"Lake Charles, LA",LA,NaN,N843MQ,NaN,NaN
479226,11.0,NaN,7,10.0,640.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2015-12-13,...,NaN,MQ,LCH,12915,"Lake Charles, LA",LA,NaN,N932MQ,NaN,NaN
479227,5.0,NaN,7,0.0,630.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2015-12-20,...,NaN,MQ,LCH,12915,"Lake Charles, LA",LA,NaN,N670MQ,NaN,NaN
479228,NaN,NaN,7,NaN,NaN,DFW,11298,"Dallas/Fort Worth, TX",TX,2015-12-27,...,NaN,MQ,LCH,12915,"Lake Charles, LA",LA,NaN,N818MQ,NaN,NaN
479229,-18.0,NaN,7,-13.0,1707.0,DFW,11298,"Dallas/Fort Worth, TX",TX,2015-12-06,...,NaN,MQ,XNA,15919,"Fayetteville, AR",AR,NaN,N534MQ,NaN,NaN

## Most Delayed Flights by origin and destination
### Grouped by the Origin and Destination airports, plus the average delay time for each route

In [34]:
df18.groupby(['ORIGIN','DEST'], as_index=False)['DEP_DELAY'].mean().sort_values(by='DEP_DELAY', ascending=False)

     ORIGIN DEST    DEP_DELAY
1927    ESC  MQT  1048.000000
4910    RDM  MFR   814.000000
3454    MDT  HPN   759.000000
1739    DSM  CID   295.000000
2244    GRB  MQT   257.000000
1904    ELM  ATL   194.000000
2648    ICT  DAY   181.000000
4       ABE  MDT   175.000000
1924    ERI  ITH   156.000000
1757    DSM  PIA   155.000000
1123    CMH  HOU   148.000000
383     AVL  TPA   147.250000
1174    CRP  BRO   147.000000
2802    JAX  TPA   144.000000
3134    LBB  SAF   134.000000
5891    SWF  PBI   122.000000
391     AVP  SFB   113.000000
1917    ELP  OKC   112.000000
6151    YNG  PIE   111.000000
6060    TVC  EWR   104.217949
3872    MSP  PVD   102.000000
2314    GTF  BZN   101.000000
1172    CPR  LAS   100.000000
4751    PIE  YNG    89.000000
2651    ICT  HYS    88.000000
2435    HRL  DAL    86.000000
2932    LAS  CPR    81.000000
98      ANC  DFW    80.043103
2478    IAD  GSO    79.666667
4977    RIC  BNA    78.413793
...     ...  ...          ...
695     BRW  ANC    -8.033582
5255    SCC  BRW    -8.700000
2049    FAI  ANC    -8.863300
3745    MSN  IAH    -9.000000
2308    GSP  PGD    -9.000000
1735    DRO  LAX    -9.230769
2899    KTN  JNU    -9.236052
4833    PSG  WRG    -9.420664
3735    MSN  BNA    -9.500000
2494    IAD  MSN    -9.500000
4261    ORD  LFT   -10.000000
4056    OAK  PVU   -10.000000
1750    DSM  LIT   -10.000000
4069    OGG  BLI   -10.038462
2336    HDN  SFO   -10.083333
6129    WRG  KTN   -10.140741
1876    EAR  DEN   -10.162791
2170    FNT  MYR   -10.181818
3963    MTJ  SLC   -10.285714
5293    SDF  TXK   -11.000000
6150    YAK  JNU   -12.192593
3737    MSN  CLE   -13.500000
1313    DAY  MYR   -13.538462
4805    PNS  CLL   -15.000000
3757    MSN  STL   -15.000000
5563    SIT  ANC   -22.000000
2790    JAX  MCO          NaN
5445    SFB  TTN          NaN
5965    TPA  MCO          NaN
6011    TTN  SFB          NaN

[6154 rows x 3 columns]

## Earliest departure flights, by origin and destination
### Grouped by origin and destination, with an average of the delay time

In [58]:
df18.groupby(['ORIGIN','DEST'], as_index=False)['DEP_DELAY'].mean().sort_values(by='DEP_DELAY', ascending=True)

     ORIGIN DEST    DEP_DELAY
5563    SIT  ANC   -22.000000
4805    PNS  CLL   -15.000000
3757    MSN  STL   -15.000000
1313    DAY  MYR   -13.538462
3737    MSN  CLE   -13.500000
6150    YAK  JNU   -12.192593
5293    SDF  TXK   -11.000000
3963    MTJ  SLC   -10.285714
2170    FNT  MYR   -10.181818
1876    EAR  DEN   -10.162791
6129    WRG  KTN   -10.140741
2336    HDN  SFO   -10.083333
4069    OGG  BLI   -10.038462
4261    ORD  LFT   -10.000000
4056    OAK  PVU   -10.000000
1750    DSM  LIT   -10.000000
2494    IAD  MSN    -9.500000
3735    MSN  BNA    -9.500000
4833    PSG  WRG    -9.420664
2899    KTN  JNU    -9.236052
1735    DRO  LAX    -9.230769
2308    GSP  PGD    -9.000000
3745    MSN  IAH    -9.000000
2049    FAI  ANC    -8.863300
5255    SCC  BRW    -8.700000
695     BRW  ANC    -8.033582
6008    TTN  PIE    -8.000000
861     CDV  YAK    -7.415441
5869    STT  EWR    -7.400000
2879    JNU  KTN    -7.333333
...     ...  ...          ...
2435    HRL  DAL    86.000000
2651    ICT  HYS    88.000000
4751    PIE  YNG    89.000000
1172    CPR  LAS   100.000000
2314    GTF  BZN   101.000000
3872    MSP  PVD   102.000000
6060    TVC  EWR   104.217949
6151    YNG  PIE   111.000000
1917    ELP  OKC   112.000000
391     AVP  SFB   113.000000
5891    SWF  PBI   122.000000
3134    LBB  SAF   134.000000
2802    JAX  TPA   144.000000
1174    CRP  BRO   147.000000
383     AVL  TPA   147.250000
1123    CMH  HOU   148.000000
1757    DSM  PIA   155.000000
1924    ERI  ITH   156.000000
4       ABE  MDT   175.000000
2648    ICT  DAY   181.000000
1904    ELM  ATL   194.000000
2244    GRB  MQT   257.000000
1739    DSM  CID   295.000000
3454    MDT  HPN   759.000000
4910    RDM  MFR   814.000000
1927    ESC  MQT  1048.000000
2790    JAX  MCO          NaN
5445    SFB  TTN          NaN
5965    TPA  MCO          NaN
6011    TTN  SFB          NaN

[6154 rows x 3 columns]

## Most delayed flights by origin, destination, and airline
### Grouped by Origin Airport, Destination, and Airline, with an average of the delay times

In [35]:
df18.groupby(['ORIGIN','DEST', 'OP_UNIQUE_CARRIER'], as_index=False)['DEP_DELAY'].mean().sort_values(by='DEP_DELAY', ascending=False)

      ORIGIN DEST OP_UNIQUE_CARRIER    DEP_DELAY
4023     ESC  MQT                OO  1048.000000
1453     BUF  LGA                OO   853.000000
6539     LGA  BOS                OO   851.000000
10127    RDM  MFR                OO   814.000000
7183     MDT  HPN                EV   759.000000
3941     DTW  TUL                EV   435.500000
9757     PHX  TUL                F9   400.000000
1268     BOS  LGA                OO   323.500000
7808     MSP  DFW                YX   300.000000
3566     DSM  CID                EV   295.000000
4642     GRK  ATL                EV   279.000000
4629     GRB  MQT                OO   257.000000
1100     BNA  MSP                EV   255.500000
2236     CMH  LGA                DL   254.000000
8903     ORD  ORF                AA   239.125000
281      ATL  CVG                EV   226.000000
1892     CLE  ORD                F9   217.000000
2345     CVG  ATL                EV   216.000000
3984     ELM  ATL                EV   194.000000
3788     DTW  LIT                EV   182.250000
5434     ICT  DAY                OO   181.000000
5680     JAX  DTW                YX   176.000000
6        ABE  MDT                OO   175.000000
3603     DSM  PHX                YV   174.500000
7895     MSP  LEX                EV   169.000000
4020     ERI  ITH                OO   156.000000
5480     ILM  LGA                9E   155.166667
3604     DSM  PIA                G4   155.000000
4809     HNL  JFK                DL   153.833333
553      ATL  SDF                EV   152.333333
...      ...  ...               ...          ...
3951     EAR  DEN                OO   -10.162791
4510     FNT  MYR                G4   -10.181818
8308     OAK  PDX                AS   -10.226277
8177     MTJ  SLC                OO   -10.285714
7671     MSN  MSP                EV   -11.000000
10865    SDF  TXK                EV   -11.000000
11929    SYR  ORD                EV   -11.000000
8192     MYR  BOS                YX   -11.750000
6569     LGA  CMH                DL   -12.000000
8190     MYR  BOS                9E   -12.000000
12331    YAK  JNU                AS   -12.192593
12187    TVC  EWR                YX   -13.000000
7646     MSN  CLE                EV   -13.500000
2574     DAY  MYR                G4   -13.538462
4302     FAR  DFW                DL   -14.000000
7685     MSN  SLC                DL   -14.000000
9947     PNS  CLL                EV   -15.000000
7687     MSN  STL                9E   -15.000000
11361    SIT  ANC                AS   -22.000000
914      BGR  EWR                UA          NaN
1452     BUF  LGA                EV          NaN
1979     CLT  CVG                MQ          NaN
5698     JAX  JFK                OO          NaN
5704     JAX  MCO                F9          NaN
6544     LGA  BUF                EV          NaN
8006     MSP  SBN                9E          NaN
10199    RDU  IND                OO          NaN
11115    SFB  TTN                G4          NaN
12032    TPA  MCO                F9          NaN
12100    TTN  SFB                G4          NaN

[12335 rows x 4 columns]

## Least delayed flights by origin, destination, and airline
### Grouped by Origin Airport, Destination, and Airline, with an average of the delay times

In [54]:
df18.groupby(['ORIGIN','DEST', 'OP_UNIQUE_CARRIER'], as_index=False)['DEP_DELAY'].mean().sort_values(by='DEP_DELAY', ascending=True)

      ORIGIN DEST OP_UNIQUE_CARRIER    DEP_DELAY
11361    SIT  ANC                AS   -22.000000
7687     MSN  STL                9E   -15.000000
9947     PNS  CLL                EV   -15.000000
4302     FAR  DFW                DL   -14.000000
7685     MSN  SLC                DL   -14.000000
2574     DAY  MYR                G4   -13.538462
7646     MSN  CLE                EV   -13.500000
12187    TVC  EWR                YX   -13.000000
12331    YAK  JNU                AS   -12.192593
6569     LGA  CMH                DL   -12.000000
8190     MYR  BOS                9E   -12.000000
8192     MYR  BOS                YX   -11.750000
10865    SDF  TXK                EV   -11.000000
11929    SYR  ORD                EV   -11.000000
7671     MSN  MSP                EV   -11.000000
8177     MTJ  SLC                OO   -10.285714
8308     OAK  PDX                AS   -10.226277
4510     FNT  MYR                G4   -10.181818
3951     EAR  DEN                OO   -10.162791
12290    WRG  KTN                AS   -10.140741
4792     HDN  SFO                OO   -10.083333
8331     OGG  BLI                AS   -10.038462
3779     DTW  LEX                DL   -10.000000
5130     IAH  BTR                UA   -10.000000
8805     ORD  LFT                YX   -10.000000
7883     MSP  JFK                AA   -10.000000
8880     ORD  MSY                OH   -10.000000
9914     PIT  ORD                EV   -10.000000
8314     OAK  PVU                G4   -10.000000
1287     BOS  MSP                AA   -10.000000
...      ...  ...               ...          ...
3984     ELM  ATL                EV   194.000000
2345     CVG  ATL                EV   216.000000
1892     CLE  ORD                F9   217.000000
281      ATL  CVG                EV   226.000000
8903     ORD  ORF                AA   239.125000
2236     CMH  LGA                DL   254.000000
1100     BNA  MSP                EV   255.500000
4629     GRB  MQT                OO   257.000000
4642     GRK  ATL                EV   279.000000
3566     DSM  CID                EV   295.000000
7808     MSP  DFW                YX   300.000000
1268     BOS  LGA                OO   323.500000
9757     PHX  TUL                F9   400.000000
3941     DTW  TUL                EV   435.500000
7183     MDT  HPN                EV   759.000000
10127    RDM  MFR                OO   814.000000
6539     LGA  BOS                OO   851.000000
1453     BUF  LGA                OO   853.000000
4023     ESC  MQT                OO  1048.000000
914      BGR  EWR                UA          NaN
1452     BUF  LGA                EV          NaN
1979     CLT  CVG                MQ          NaN
5698     JAX  JFK                OO          NaN
5704     JAX  MCO                F9          NaN
6544     LGA  BUF                EV          NaN
8006     MSP  SBN                9E          NaN
10199    RDU  IND                OO          NaN
11115    SFB  TTN                G4          NaN
12032    TPA  MCO                F9          NaN
12100    TTN  SFB                G4          NaN

[12335 rows x 4 columns]

## Group by Origin, Destination, and Date to find potential bad weather days

In [39]:
df18.groupby(['ORIGIN','DEST', 'FL_DATE'], as_index=False)['DEP_DELAY'].mean().sort_values(by='DEP_DELAY', ascending=False)

        ORIGIN DEST     FL_DATE  DEP_DELAY
514896     HNL  PPG  2018-02-09     2482.0
1030031    PPG  HNL  2018-02-09     2468.0
422134     EGE  JFK  2018-01-11     2007.0
511824     HNL  JFK  2018-01-03     1682.0
422370     EGE  MIA  2018-03-04     1552.0
143314     BQN  JFK  2018-01-06     1489.0
767486     MEI  ORD  2018-01-03     1424.0
373123     DFW  PIB  2018-01-03     1416.0
944051     PBI  ACY  2018-04-05     1394.0
23750      ASE  DFW  2018-06-02     1370.0
422348     EGE  MIA  2018-02-10     1366.0
597501     ITO  LAX  2018-06-14     1363.0
1045970    RDM  PHX  2018-04-27     1337.0
511158     HNL  IAD  2018-03-30     1333.0
597362     ITO  LAX  2018-01-26     1313.0
456095     FAR  MSP  2018-04-14     1308.0
780427     MHT  ORD  2018-01-22     1297.0
583552     IMT  DTW  2018-05-16     1288.0
1116209    SDF  DTW  2018-01-12     1283.0
348065     DFW  BZN  2018-05-04     1273.0
513608     HNL  OAK  2018-03-31     1260.0
331449     DEN  OGG  2018-06-29     1254.0
176261     BZN  DFW  2018-05-04     1249.0
836136     MSP  MLI  2018-05-29     1248.0
373258     DFW  PIB  2018-05-18     1238.0
1080986    SAF  PHX  2018-01-15     1232.0
767621     MEI  ORD  2018-05-18     1222.0
82178      AVL  TPA  2018-09-09     1222.0
627543     KOA  DEN  2018-02-15     1216.0
9295       ACY  ATL  2018-08-18     1211.0
...        ...  ...         ...        ...
1288813    XNA  DCA  2018-03-20        NaN
1288814    XNA  DCA  2018-03-21        NaN
1289440    XNA  EWR  2018-01-03        NaN
1289441    XNA  EWR  2018-01-04        NaN
1289452    XNA  EWR  2018-01-16        NaN
1289493    XNA  EWR  2018-03-02        NaN
1289498    XNA  EWR  2018-03-07        NaN
1289511    XNA  EWR  2018-03-21        NaN
1289523    XNA  EWR  2018-04-02        NaN
1289524    XNA  EWR  2018-04-03        NaN
1289546    XNA  EWR  2018-04-25        NaN
1289563    XNA  EWR  2018-05-15        NaN
1289569    XNA  EWR  2018-05-22        NaN
1289577    XNA  EWR  2018-05-31        NaN
1289619    XNA  EWR  2018-07-15        NaN
1289620    XNA  EWR  2018-07-16        NaN
1289629    XNA  EWR  2018-07-25        NaN
1289649    XNA  EWR  2018-08-14        NaN
1289692    XNA  EWR  2018-09-26        NaN
1289712    XNA  IAH  2018-01-16        NaN
1290072    XNA  LGA  2018-01-04        NaN
1290073    XNA  LGA  2018-01-05        NaN
1290125    XNA  LGA  2018-03-07        NaN
1290137    XNA  LGA  2018-03-21        NaN
1291187    YAK  CDV  2018-01-07        NaN
1291223    YAK  CDV  2018-02-12        NaN
1291237    YAK  CDV  2018-02-26        NaN
1291246    YAK  CDV  2018-03-07        NaN
1291498    YAK  JNU  2018-02-15        NaN
1291524    YAK  JNU  2018-03-13        NaN

[1292001 rows x 4 columns]

## Weather delays again, but this time using the WEATHER_DELAY column

In [53]:
# Fill NaNs as zeros so the weather delay column averages properly
df18.fillna(0).groupby(['ORIGIN','DEST', 'FL_DATE'], as_index=False)['WEATHER_DELAY'].mean().sort_values(by='WEATHER_DELAY', ascending=False)

        ORIGIN DEST     FL_DATE  WEATHER_DELAY
514896     HNL  PPG  2018-02-09         2475.0
511824     HNL  JFK  2018-01-03         1682.0
583552     IMT  DTW  2018-05-16         1287.0
1156992    SFO  MMH  2018-02-11         1203.0
583691     IMT  MSP  2018-01-22         1186.0
622013     JFK  SAT  2018-05-15         1100.0
813499     MSN  EWR  2018-03-05         1078.0
594023     INL  MSP  2018-05-29         1030.0
305891     DCA  SLC  2018-03-02          993.0
560753     IAH  GSP  2018-01-11          970.0
262663     CVG  MKE  2018-05-15          956.0
1034141    PSP  MSP  2018-01-22          953.0
1209779    SLN  ORD  2018-06-22          951.0
904181     ORD  CKB  2018-06-19          944.0
8456       ACK  LGA  2018-07-17          940.0
546769     IAD  PWM  2018-06-02          931.0
1048790    RDU  CMH  2018-05-11          926.0
1189333    SLC  BTM  2018-02-17          916.0
711106     LIT  DEN  2018-06-24          910.0
839519     MSP  PIA  2018-01-07          888.0
532910     HRL  MSP  2018-02-24          887.0
542070     IAD  JAX  2018-08-01          872.0
185080     CHA  DTW  2018-07-29          850.0
544931     IAD  OKC  2018-08-02          838.0
544986     IAD  OKC  2018-09-26          834.0
613502     JFK  EGE  2018-02-23          824.0
401681     DTW  HPN  2018-05-19          822.0
544868     IAD  OKC  2018-05-31          815.0
841722     MSP  ROC  2018-09-06          812.0
819714     MSP  BMI  2018-04-03          808.0
...        ...  ...         ...            ...
441860     EWR  MDW  2018-05-20            0.0
441859     EWR  MDW  2018-05-19            0.0
441858     EWR  MDW  2018-05-18            0.0
441857     EWR  MDW  2018-05-17            0.0
441855     EWR  MDW  2018-05-15            0.0
441854     EWR  MDW  2018-05-14            0.0
441853     EWR  MDW  2018-05-13            0.0
441852     EWR  MDW  2018-05-12            0.0
441851     EWR  MDW  2018-05-11            0.0
441850     EWR  MDW  2018-05-10            0.0
441866     EWR  MDW  2018-05-26            0.0
441868     EWR  MDW  2018-05-28            0.0
441886     EWR  MDW  2018-06-15            0.0
441869     EWR  MDW  2018-05-29            0.0
441885     EWR  MDW  2018-06-14            0.0
441884     EWR  MDW  2018-06-13            0.0
441883     EWR  MDW  2018-06-12            0.0
441882     EWR  MDW  2018-06-11            0.0
441881     EWR  MDW  2018-06-10            0.0
441879     EWR  MDW  2018-06-08            0.0
441878     EWR  MDW  2018-06-07            0.0
441877     EWR  MDW  2018-06-06            0.0
441876     EWR  MDW  2018-06-05            0.0
441875     EWR  MDW  2018-06-04            0.0
441874     EWR  MDW  2018-06-03            0.0
441873     EWR  MDW  2018-06-02            0.0
441872     EWR  MDW  2018-06-01            0.0
441871     EWR  MDW  2018-05-31            0.0
441870     EWR  MDW  2018-05-30            0.0
1292000    YUM  PHX  2018-09-30            0.0

[1292001 rows x 4 columns]